apiVersion: "k8s.f5net.com/v1"
kind: F5BigFwPolicy
metadata:
  name: "cnf-fw-policy"
spec:
  rule:
    # - name: allow-10-10-http
    #   action: "accept"
    #   logging: true
    #   ipProtocol: tcp
    #   source:
    #     addresses:
    #       - "10.1.20.31/24"
    #   destination:
    #     ports:
    #       - "80"
    - name: drop-all
      action: "drop"
      logging: true
      ipProtocol: any
      source:
        addresses:
          - "::0/0"
          - "0.0.0.0/0"
