apiVersion: v1
kind: Pod
metadata:
  name: pod-in-internet
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name" : "internet",
              "interface": "macvlan1" }
    ]'
spec:
  containers:
  - name: pod-case-06
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-2-in-internet
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name" : "internet",
              "interface": "macvlan1" }
    ]'
spec:
  containers:
  - name: pod-case-06
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
---

apiVersion: v1
kind: Pod
metadata:
  name: pod-in-subscriber
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name" : "subscriber",
              "interface": "macvlan1" }
    ]'
spec:
  containers:
  - name: pod-case-06
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
