imageCredentials:
  name: f5ingress-regsecret
  registry: "registry.gitlab.com/etlawby/my-spk"
  username: "gitlab+deploy-token-3693703"
  password: "T3d7BTgxv9HgchX89k3a"
  email: "a.bargery@f5.com"

controller:
  image:
    repository: "registry.gitlab.com/etlawby/my-spk"
  fluentbit_sidecar:
    enabled: false

afm:
  enabled: true
  fluentbit_sidecar:
    enabled: false
  pccd:
    enabled: true
    securityContext:
      allowPrivilegeEscalation: true
      runAsUser: 0
    image:
      repository: registry.gitlab.com/etlawby/my-spk

tmm:
  resources:
    limits:
      cpu: 1
  prometheus:
    create: false
  hugepages:
    enabled: false
  image:
    repository: "registry.gitlab.com/etlawby/my-spk"
    pullPolicy: IfNotPresent

  pod:
    annotations:
      k8s.v1.cni.cncf.io/networks: '[{
        "name": "subscriber"
      },
      {
        "name": "internet"
      }]'

  customEnvVars:
  - name: CONFIG_VIEWER_ENABLE
    value: "TRUE"
  - name: TMM_MAPRES_DELAY_MS
    value: "6000"
  - name: TMM_MAPRES_VERBOSITY
    value: "debug"
  - name: TMM_MAPRES_PREFER_SOCK
    value: "TRUE"
  - name: TMM_CALICO_ROUTER
    value: "default"
  - name: TMM_MAPRES_ADDL_VETHS_ON_DP
    value: "TRUE"
  - name: TMM_IGNORE_GATEWAYS 
    value: "TRUE"

  k8sprobes:
    enables: false

  dynamicRouting:
    enabled: true
    tmmRouting:
      image:
        repository: "registry.gitlab.com/etlawby/my-spk"
        pullPolicy: IfNotPresent
      config:
        bgp:
          asn: 100
          maxPathsEbgp: 4
          maxPathsIbgp: 'null'
          hostname: cnf-bgp
          neighbors:
          - ip: 10.1.200.5
            asn: 200
            ebgpMultihop: 10
            acceptsIPv4: true
            acceptsIPv6: true
    tmrouted:
      image:
        repository: "registry.gitlab.com/etlawby/my-spk"
        pullPolicy: IfNotPresent

  service:
    type: ClusterIP

debug:
  image:
    repository: "registry.gitlab.com/etlawby/my-spk"
    pullPolicy: IfNotPresent

# this is required to stop subchart running    
f5-toda-logging:
  enabled: false


